### ISSUE TITLE
Návrh implementácie

### ISSUE THREAD

**Issue by mackova140** [TIS2021-FMFI/produktivita-linky#11]
Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

Takže  UML component diagram
            UML class diagram
            UML state alebo UML sequence diagram

**Comment by Us3capp** [comment]
Prikladám link k návrhu implementácie:
https://docs.google.com/document/d/1umayoGDa2KEY_asNNGmwmBHYKJFy9_qMy5bCnamxPeo/edit?usp=sharing
