### ISSUE TITLE
Návrh GUI

### ISSUE THREAD

**Issue by DarthKirtap** [TIS2021-FMFI/produktivita-linky#2]
Navrhnút prototyp GUI

**Comment by mackova140** [comment]
<img width="811" alt="Snímka obrazovky 2021-11-04 o 9 33 54" src="https://user-images.githubusercontent.com/79453298/140285697-ad92d65a-5b1a-4bbd-b0c3-8cde808210f1.png">
<img width="811" alt="Snímka obrazovky 2021-11-04 o 9 41 15" src="https://user-images.githubusercontent.com/79453298/140285703-c60f92b9-8d52-4b70-b3b8-97877903907a.png">
<img width="813" alt="Snímka obrazovky 2021-11-04 o 9 55 02" src="https://user-images.githubusercontent.com/79453298/140285705-cb85cac5-37c6-4140-818e-ddc02e996c8c.png">

**Comment by mackova140** [comment]
<img width="813" alt="Snímka obrazovky 2021-11-04 o 10 02 28" src="https://user-images.githubusercontent.com/79453298/140286331-f49f80c5-7406-4e6a-8aa1-2cfff28b77c9.png">

**Comment by mackova140** [comment]
<img width="813" alt="Snímka obrazovky 2021-11-04 o 11 36 23" src="https://user-images.githubusercontent.com/79453298/140299511-fe2a1f8a-1a8d-462d-9046-1277d0db471a.png">

**Comment by mackova140** [comment]
<img width="813" alt="Snímka obrazovky 2021-11-05 o 12 44 05" src="https://user-images.githubusercontent.com/79453298/140505552-678080e0-286f-4734-8bbc-0ec7c143b20c.png">

**Comment by mackova140** [comment]
Sem pripínam finálne GUI ktoré čaká na schválenie od gefca :)
<img width="809" alt="Snímka obrazovky 2021-11-10 o 10 36 30" src="https://user-images.githubusercontent.com/79453298/141089038-e83b5277-e0fa-4433-9902-70e22bba3976.png">
<img width="837" alt="Snímka obrazovky 2021-11-09 o 19 54 27" src="https://user-images.githubusercontent.com/79453298/141089041-1be58115-3564-4a02-85a1-832b40dea4f1.png">
<img width="578" alt="Snímka obrazovky 2021-11-10 o 10 41 41" src="https://user-images.githubusercontent.com/79453298/141089240-61a05b60-0d6c-4fc9-b21e-3c0381b87645.png">

**Comment by mackova140** [comment]
Pri poslednom hovore nám oznámili par zmien čo sa týkajú GUI:
- zapracovanie loga
- viac kontrastné farby ...
- denna statistika aby bola vyssie (vamenená s týzdennou)

**Comment by mackova140** [comment]
<img width="641" alt="operator" src="https://user-images.githubusercontent.com/79453298/142760416-521754cb-3313-40a2-92d1-a028de16df7f.png">
<img width="769" alt="admin" src="https://user-images.githubusercontent.com/79453298/142760418-8f3f0bd8-d4bc-4446-8a3d-10d4f5599925.png">
<img width="641" alt="Snímka obrazovky 2021-11-21 o 12 44 03" src="https://user-images.githubusercontent.com/79453298/142760440-793e2613-3d1a-4a54-8270-50a6abe8b9d3.png">

**Comment by mackova140** [comment]
Uzatváram túto vetvu a posledné návrhy pridám samostatne aby v tom nebol neporiadok
