### ISSUE TITLE
Rozdelenie práce

### ISSUE THREAD

**Issue by mackova140** [TIS2021-FMFI/produktivita-linky#30]
Rozpísanie práce, ktorú bude ešte potrebné vykonať.
Písať návrhy može každý jeden a automaticky sa budeme pripisovať k daným úlohám.

**Comment by Zaikner** [comment]
-> db ->vypočítať, kolko paliet by sa umylo, keby linka nestojí(všetky dôvôody), bude to v grafoch
->db->vypočítať, ako rýchlo umývaju, a ako rýchlo by mali etc..
-> export do csv
-> prepojit gui, logic a db
-> urobiť Refreshing, každú minutú, dbať na to, aby sa všetky dáta preliali z t_raw_data do t_raw_data history, logy z iného dňa premazávať, queries už maš hotove , ide o to už len spúštatˇich-> urobi Paťo
-> testovacia App -> súrne i guess - Tina
-> ostatne queries - stop linky, ukoncenie zmeny,, nova zmena,zmena ciela -Filip
-> prestávky - Paťo dačo spomínal
-> vyhodenie oznamu ze prebieha udržba alebo prestávka
