### ISSUE TITLE
Vytvoriť katalóg požiadaviek

### ISSUE THREAD

**Issue by Us3capp** [TIS2021-FMFI/produktivita-linky#6]

**Comment by mackova140** [comment]
@mackova140 prerozdelíme si časti a spíšeme v zdieľanom dokumente, doplníme informácie podľa zodpovedaných otázok z mailovej komunikácie. Následne kazdý skontroluje ostatných text.

**Comment by mackova140** [comment]
1 kapitola - Tina doplní podľa spísaného nižšie
2 kapitola - Natália
3 kapitola - Patrik + Filip

- následne všetci kontrolujú všetko! 
- @Us3capp na základe poznámok z nahrávky, Tina ju postne najnesôr vo štvrtok (7.5.2021)
- do konca týždna chceme mať prvotnú verzio, ltoru budeme následne modifikovať

**Comment by Zaikner** [comment]
Dačo som tam popísal :) Dokončím keď budem mať prepis stretnutia a odpoveď na otázky od GEFCO. :)

**Comment by mackova140** [comment]
Takže časti 2 a 3 sú + - hotové. @DarthKirtap prosím ťa skontroluj a doplň čo ti napadne. @Us3capp ešte dokončí 1 kapitolu

**Comment by mackova140** [comment]
Už čaká len na odsuhlasenie od gefca (po úprave)

**Comment by Zaikner** [comment]
Katalog odsúhlasený, zatváram.
